# Numpy

In [5]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Array created using list:\n", a)

Array created using list
 [[1 2 3]
 [4 5 6]]


In [7]:
b = np.array((1 , 3, 2)) 
print ("Array created using tuple:\n", b) 

Array created using tuple:
 [1 3 2]


In [8]:
c = np.zeros((3, 4))
print("Array created with all zeros:\n", c)

Array created with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
e = np.random.random((2, 2)) 
print ("Random array:\n", e) 

Random array:
 [[0.53209377 0.06338693]
 [0.42814874 0.4459505 ]]


In [12]:
import numpy as np 
  
arr = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]]) 
  
temp = arr[:2, :2] 
print ("Slicing of an 4 dimensional arrya:\n", temp) 

Slicing of an 4 dimensional arrya:
 [[-1.   2. ]
 [ 4.  -0.5]]


In [14]:
import numpy as np 
  
a = np.array([1, 2, 5, 3]) 
  
# add 1 to every element 
print ("Adding 1 to every element:", a+1) 
  
# subtract 5 from each element 
print ("Subtracting 5 from each element:", a-5) 
  
# multiply each element by 2 
print ("Multiplying each element by 2:", a*2) 
  
# square each element 
print ("Squaring each element:", a**2) 

Adding 1 to every element: [2 3 6 4]
Subtracting 5 from each element: [-4 -3  0 -2]
Multiplying each element by 2: [ 2  4 10  6]
Squaring each element: [ 1  4 25  9]
[1 2 5 3]


In [16]:
#Transpose of an array 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 
  
print ("Original array:\n", a) 
print ("Transpose of array:\n", a.T) 

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]
